version: '2'
services:
  client:
    build: ./client
    image: client-image:v1
    ports:
     - '3001:3001'
    depends_on:
     - api
    container_name: docker-client
    tty: true

  api:
    build: ./api
    image: api-image:v1
    ports:
     - '3002:3002'
    depends_on:
     - elasticsearch-api
    container_name: docker-api
    tty: true

  elasticsearch-api:
    image: elasticsearch
    ports:
      - '80:80'
      - '9200:9200'
    container_name: docker-elasticsearch
    command: bash -c "bash /docker-entrypoint.sh elasticsearch"  
    tty: true